# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('序号', models.AutoField(primary_key=True, serialize=False)),
                ('链接', models.TextField(blank=True)),
                ('线报', models.TextField(blank=True)),
                ('权限', models.TextField(blank=True)),
                ('时间', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'table1',
            },
        ),
    ]
