# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDcoupon',
            fields=[
                ('序号', models.AutoField(primary_key=True, serialize=False)),
                ('价值', models.FloatField(blank=True)),
                ('品类', models.TextField(blank=True)),
                ('限制', models.FloatField(blank=True)),
                ('图片链接', models.TextField(blank=True)),
                ('领取链接', models.TextField(blank=True)),
                ('页面链接', models.TextField(blank=True)),
                ('时间', models.TextField(blank=True)),
                ('折扣率', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'jdcoupon',
            },
        ),
    ]
